Coding/Core.Backoffice/Controllers/ActionScriptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Common;
using Core.DAL.Models;
using Core.library;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Wangkanai.Detection;

namespace Core.Backoffice.Controllers
{
    [Authorize]
    [ActiveUserFilter]
    public class ActionScriptsController :  BaseController
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IHttpContextAccessor _accessor;
        private readonly IBrowserResolver _browser;
        private static string IpAddress;
        private static string Browser;
        private readonly IMemoryCache _cache;
        public ActionScriptsController(IWebHostEnvironment environment, IHttpContextAccessor httpContextAccessor, IBrowserResolver browserDetector, IMemoryCache memoryCache)
        {
            _environment = environment;
            _accessor = httpContextAccessor;
            _browser = browserDetector;
            IpAddress = _accessor.HttpContext.Connection.RemoteIpAddress.ToString();
            Browser = _browser.Browser.Type.ToString();
            _cache = memoryCache;
        }
        [HttpPost]
        public JsonResult UpdateSorting(string MenuDisplayID, string MenuID, string SortingBy,int ActionType)
        {
            bool Results = false;
            if(ActionType ==1)
                Results = MenuDisplayData.Post.UpdateSortingBy(Int32.Parse(MenuDisplayID), Int32.Parse(MenuID), Int32.Parse(SortingBy),UserName, IpAddress, Browser);
            else
                Results = MenuDisplayData.Post.UpdateSortingType(Int32.Parse(MenuDisplayID), Int32.Parse(MenuID), Boolean.Parse(SortingBy), UserName, IpAddress, Browser);

            return Json(new { status = Results, message = "พบข้อผิดพลาดกรุณาลองใหม่ หรือ ติดต่อผู้ดูแลระบบ"});
        }

        [HttpPost]
        public JsonResult Delete(int RoleGroupID)
        {
            try
            {
                var Items = RoleData.Post.Delete(RoleGroupID, UserName, IpAddress, Browser);
                return Json(new { status = true, Items });
            }
            catch (Exception ex)
            {
                return Json(new { status = true, message = ex.Message.ToString() });
            }
        }
        [HttpPost]
        public JsonResult UpdateSequence(int ID, string Menuname, string MenuType, string Seq)
        {
            ResponseJson ResponseData = new ResponseJson();
            try
            {
                switch (MenuType)
                {
                    case "BANNER":
                        ResponseData = BannerData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "JOBS":
                        ResponseData = JobPositionData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "POSTS":
                        ResponseData = PostData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "FAQ":
                        ResponseData = FaqData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "DOWNLOAD":
                        ResponseData = DownloadFormData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "RSSFeed":
                        ResponseData = RSSFeedData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "STAFF":
                        ResponseData = StaffData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "WBTOPIC":
                        ResponseData = WBTopicData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "SHORTCUT":
                        ResponseData = MenuFrontData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MENU":
                        ResponseData = MenuBackofficeData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        SetNewMenu(UserRoleGroupId);
                        break;
                    case "CATEGORY":
                        ResponseData = CategoryData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MASTER":
                        ResponseData = MasterData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "PROJECTS":
                        ResponseData = ProjectsData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                        
                    default:
                        ResponseData.Result = false;
                        ResponseData.MessageError = "Default";
                        break;
                }
                return Json(ResponseData);
            }
            catch (Exception ex)
            {
                return Json(new { status = true, message = ex.Message.ToString() });
            }
        }
        [HttpPost]
        public JsonResult UpdateStatus(int ID,string Menuname, string MenuType, string state)
        {
            ResponseJson ResponseData = new ResponseJson();
            try
            {
                
                switch (MenuType)
                {
                    case "CATEGORY":    ResponseData = CategoryData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "BANNER":
                                        ResponseData = BannerData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "JOBS":
                                        ResponseData = JobPositionData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "POSTS":
                                        ResponseData = PostData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "FAQ":
                                        ResponseData = FaqData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "DOWNLOAD":
                                        ResponseData = DownloadFormData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "RSSFeed":
                                        ResponseData = RSSFeedData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "STAFF":
                        ResponseData = StaffData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                 
                    case "WBTOPIC":
                        ResponseData = WBTopicData.Post.Forbidden(ID, bool.Parse(state),"", UserName, IpAddress, Browser, Menuname);
                        break;
                    case "WBWAITTING":
                        ResponseData = WBTopicData.Post.Approved(ID, bool.Parse(state),"", UserName, IpAddress, Browser, Menuname);
                        break;
                     case "COMPLAINTTYPE":
                        ResponseData = ComplaintTypeData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "SHORTCUT":
                        ResponseData = MenuFrontData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MENU":
                        ResponseData = MenuBackofficeData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        SetNewMenu(UserRoleGroupId);
                        break;
                    case "ROLEGROUP":
                        ResponseData = RoleData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                 
                    case "MEMBER":
                        ResponseData = MemberData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "WBREPLY":
                        ResponseData = WBReplyData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "CHANNELCOMMENTTYPE":
                        ResponseData = ChannelCommentTypeData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MASTER":
                        ResponseData = MasterData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "USER":

Coding/Core.Backoffice/Controllers/GoToFile/GoToFileController.cs
using System;
using System.Linq;
using Core.Common;
using Core.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Wangkanai.Detection;

namespace Core.Backoffice.Controllers
{
    [Authorize]
    [ActiveUserFilter]
    public class GoToFileController : BaseController
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IHttpContextAccessor _accessor;
        private readonly IBrowserResolver _browser;
        private static string IpAddress;
        private static string Browser;
        private readonly IMemoryCache _cache;
        
        public GoToFileController(IWebHostEnvironment environment, IHttpContextAccessor httpContextAccessor, IBrowserResolver browserDetector,IMemoryCache memoryCache)
        {
            _environment = environment;
            _accessor = httpContextAccessor;
            _browser = browserDetector;
            IpAddress = _accessor.HttpContext.Connection.RemoteIpAddress.ToString();
            Browser = _browser.Browser.Type.ToString();
            _cache = memoryCache;
        }
        public IActionResult Index(string menuname)
        {
            string name_menu = "";
            try
            {
                Tm_Menu menuObj = MenuBackofficeData.Get.ByPermalinkWithRole(menuname, UserName);
                if (menuObj.Role == "N")
                    return RedirectToAction("Index", "Permission", new { MenuName = "401" });

                int MenuID = menuObj?.ID ?? 0;
                name_menu = menuObj?.Menuname ?? "ไม่พบเมนู";
                ViewBag.Title = name_menu;
                ViewBag.MenuID = MenuID;
                ViewBag.Menuname = menuname;
                ViewBag.Role = menuObj.Role;
                if (MenuID == 0)
                    return RedirectToAction("Index", "Errorpage", new { MenuName = "404" });
                Banner getMain = BannerData.Get.MainBannerByMenuId(MenuID);
                var main = getMain!=null ? getMain : new Banner();
                int ID = main.ID;
                var obj = BannerData.Get.BannerById(ID).ToList();
                main = main == null ? new Banner() : main;
                main.MenuID = MenuID;
                main.lstBanner = obj;
                string logDescription = "";
                if(obj.Count > 0)
                {
                    logDescription = "ดูรายละเอียดข้อมูล ดาวน์โหลดไฟล์ Name : "+obj.FirstOrDefault().Menuname;
                }
                LogTransaction.SaveLog(ID, LogTransaction.Get.ActivityType.View, name_menu, UserName, logDescription, IpAddress, Browser);
                return View("~/Views/GoToFile/Index.cshtml", main);
            }
            catch (Exception ex)
            {
                LogTransaction.SaveLog(0, LogTransaction.Get.ActivityType.Error, name_menu, UserName, ex.Message, IpAddress, Browser);
            }
            return RedirectToAction("Index", new { Menuname = menuname });
        }
        [HttpPost]
        public ActionResult Index(Banner banner)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    var main = BannerData.Post.AddOrUpdate(banner,UserName, IpAddress, Browser);
                    foreach(var o in banner.lstBanner)
                    {
                        o.BannerID = main.ID;
                    }
                    var detail = BannerData.Post.DetailAddOrUpdate(banner.lstBanner, UserName,2, IpAddress, Browser);
                    main.lstBanner = detail;
                    return RedirectToAction("Index", new { Menuname = main.Menuname });
                }
                catch (Exception ex)
                {
                    LogTransaction.SaveLog(banner.ID, LogTransaction.Get.ActivityType.Error, banner.Menuname, UserName, ex.Message, IpAddress, Browser);
                   
                }
            }
                return View("~/Views/GoToFile/Index.cshtml", banner);
        }
    }
}

Coding/Core.Backoffice/ViewComponent/LanguageTabViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Core.Common;
using Core.DAL.Models;
using Core;
using Core.library;

namespace Core.Backoffice.Controllers
{
    public class LanguageTabViewComponent : ViewComponent
    {
        private readonly IMemoryCache _cache;
        public LanguageTabViewComponent(IMemoryCache memoryCache)
        {
            _cache = memoryCache;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (!_cache.TryGetValue("LanguageList", out List<Languages> obj))
            {
                obj = LanguageData.GetByActive();
                MemoryCacheEntryOptions options = new MemoryCacheEntryOptions
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(365), // cache will expire in 25 seconds   TimeSpan.FromSeconds(25)
                    SlidingExpiration = TimeSpan.FromDays(365) // caceh will expire if inactive for 5 seconds    FromSeconds(5)
                };
                options.RegisterPostEvictionCallback(Callback, "Some state info");
                _cache.Set("LanguageList", obj, TimeSpan.FromDays(365));
           }
            return await Task.FromResult((IViewComponentResult)View("Default", obj));
        }
        private void Callback(object key, object value, EvictionReason reason, object state)
        {
            Console.WriteLine("Evicted");
        }
    }
}

Coding/Core.Backoffice/Views/GoToFile/Index.cshtml
@model Core.DAL.Models.Banner
@{
    ViewBag.Title2 = "รายละเอียดข้อมูล"+ViewBag.Title;
    string role = (String)ViewBag.Role;

 }
<style>
    .switchBootstrap {
        min-width: 450px !important;
        width: 200px !important;
    }

    .kv-file-remove {
        display: none;
    }
    .or {
        display: flex;
        justify-content: center;
        align-items: center;
        color: grey;
    }

        .or:after,
        .or:before {
            content: "";
            display: block;
            background: grey;
            width: 30%;
            height: 1px;
            margin: 0 10px;
        }
</style>
<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">@ViewBag.Title</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index","Home")">หน้าหลัก</a>
                    </li>
                    <li class="breadcrumb-item active">
                        @ViewBag.Title2
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <div class="content-header-right col-md-3 col-12">
        <div class="btn-group float-md-right">
            <a href="@Url.Action("Index", new {menuname = ViewBag.Menuname})" class="btn btn-social btn-min-width mr-1 mb-1 btn-secondary"><i class="la la-angle-left"></i> กลับ &nbsp;&nbsp;</a>
        </div>
    </div>
</div>
<div class="content-body" id="Cont">
    <section id="basic-form-layouts">
        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-content collapse show">
                        <div class="card-body">

                            @using (Html.BeginForm("Manage", "Banner", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.HiddenFor(model => Model.MenuID)
                                @Html.HiddenFor(model => Model.CreatedDate)
                                @Html.HiddenFor(model => Model.CreatedBy)
                                @Html.HiddenFor(model => Model.ID)
                                @Html.HiddenFor(model => Model.Menuname)
                                <div class="card-content">
                                    <ul class="nav nav-tabs nav-underline nav-top-border no-hover-bg">
                                        @await Component.InvokeAsync("LanguageTab")
                                    </ul>

                                    <div class="tab-content px-1 pt-1">
                                        @foreach (var itemdetail in Model.lstBanner)
                                        {
                                            itemdetail.BannerID = Model.ID;
                                            itemdetail.MenuID = Model.MenuID;
                                            itemdetail.Menuname = Model.Menuname;
                                            await Html.RenderPartialAsync("~/Views/GoToFile/_Index.cshtml", itemdetail);
                                        }
                                        <hr />
                                        <div class="row justify-content-center">

                                            <div class="form-group row">
                                                
                                                <div class="col-md-12">
                                                    <label for="active">สถานะการเผยแพร่</label>
                                                   
                                                    <div class="col-12">
                                                        @Html.CheckBoxFor(model => model.Actived, new { @id = "active", @class = "StatePublish" })
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="form-actions text-right">
                                            <button type="submit" class="btn btn-info btn-min-width btn-glow mr-1 mb-1 "><i class="ft-save"></i> บันทึก</button>
                                            <button type="reset" class="btn btn-secondary btn-min-width btn-glow mr-1 mb-1 "><i class="ft-reset"></i> คืนค่า</button>
                                        </div>
                                    </div>
                                </div>
                              }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section SecAjaxConfig{
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery/dist/jquery.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery-validation/dist/jquery.validate.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery-unobtrusive-ajax/jquery.unobtrusive-ajax.js")"></script>
}
@section Scripts{
    

    <script async type="text/javascript" src="@Url.Content("~/app-assets/js/MasterCustomFile.js")"></script>
    <script>
        $(function () {
             @if (role != "M")
               {
                   @: $("input, select, textarea, button").attr("disabled", true);
                   @:  $("button[type='submit'], button[type='reset'], input[type='submit'], input[type='reset']").remove();
                   @:  $(".SortingType, .switchForbidden, .bt-menustatus, .bt-status, .StatePublish, .switchACTIVE").each(function () { $(this).bootstrapSwitch('disabled', true); });
                    @:  $(".btn-social, .bt-delete, .or, .kv-file-remove").remove();
                   @: if ($('.summernote').length > 0) { $('.summernote').summernote('disable'); }
                   @: $('a[title="Edit"]').each(function () {$(this).attr('title', 'View'); $(this).find('span.la.la-pencil-square-o').each(function () { $(this).removeClass('la la-pencil-square-o'); $(this).addClass('la la-eye'); }); });
               }
        })
        function delf(i) {
            var urlz = "@Url.Action("RemoveFile", "ActionScripts", new { FileID = Model.ID.ToString() })";
            $.ajax({
                type: "GET",
                url: urlz,
                dataType: 'json',
                data: {
                    i: i
                },
                success: function (response) {
                    if (response != null) {
                        return true;
                    }
                    return false;
                }
            });
        }
        $(document).ready(function () {
            if ($('.fileImage').length > 0) {
                $('.fileImage').attr("accept", "image/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx");



            }

        })
    </script>
}