Coding/Core.Backoffice/Controllers/PanelSyetem/SettingFileController.cs
using System;
using System.Collections.Generic;
using Core.Common;
using Core.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Wangkanai.Detection;

namespace Core.Backoffice.Controllers
{
    [Authorize]
    [ActiveUserFilter]
    public class SettingFileController : BaseController
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IHttpContextAccessor _accessor;
        private readonly IBrowserResolver _browser;
        private readonly IMemoryCache _cache;
        public SettingFileController(IWebHostEnvironment environment, IHttpContextAccessor httpContextAccessor, IBrowserResolver browserDetector, IMemoryCache memoryCache)
        {
            _environment = environment;
            _accessor = httpContextAccessor;
            _browser = browserDetector;
            _cache = memoryCache;
        }
        [Authorize]
        public IActionResult Index(string menuname)
        {
            ViewBag.Title = "ตั้งค่าไฟล์";
            ViewBag.MenuID = 70;
            string name_menu = "";
            Tm_Menu menuObj = MenuBackofficeData.Get.ByPermalinkWithRole(menuname, UserName);
            if (menuObj.Role == "N")
                return RedirectToAction("Index", "Permission", new { MenuName = "401" });

            int MenuID = menuObj?.ID ?? 0;
            name_menu = menuObj?.Menuname ?? "ไม่พบเมนู";
            ViewBag.Title = name_menu;
            ViewBag.MenuID = MenuID;
            ViewBag.Menuname = menuname;
            ViewBag.Role = menuObj.Role;
            return View("~/Views/PanelSystem/SettingFile/Index.cshtml", SettingFileData.Get.All());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public JsonResult Index(SettingFiles Obj, List<int> AllowTypeFileID)
        {
            try
            {
                Obj.AllowTypeFile = String.Join(",", AllowTypeFileID);
                SettingFileData.save.AddOrUpdate(Obj, UserName, _accessor.HttpContext.Connection.RemoteIpAddress.ToString(), _browser.Browser.Type.ToString());

                //_cache.Set("SettingFile", SettingFileData.Get.All(), TimeSpan.FromDays(365));
                return Json(new { status = true, location = Url.Action("Index", "SettingFile") });
            }
            catch (Exception ex)
            {
                return Json(new { status = true, message = ex.Message.ToString() });
            }
        }

    }
}

Coding/Core.Backoffice/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Core.Common;
using Core.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Wangkanai.Detection;

namespace Core.Backoffice.Controllers
{
    [Authorize]
    [ActiveUserFilter]
    public class PostsController : BaseController
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IHttpContextAccessor _accessor;
        private readonly IBrowserResolver _browser;
        private static string IpAddress;
        private static string Browser;
        private readonly IMemoryCache _cache;

        public PostsController(IWebHostEnvironment environment, IHttpContextAccessor httpContextAccessor, IBrowserResolver browserDetector, IMemoryCache memoryCache)
        {
            _environment = environment;
            _accessor = httpContextAccessor;
            _browser = browserDetector;
            IpAddress = _accessor.HttpContext.Connection.RemoteIpAddress.ToString();
            Browser = _browser.Browser.Type.ToString();
            _cache = memoryCache;
        }
        // GET: /<controller>/
        public IActionResult Index(string menuname)
        {
            string name_menu = "";
            Tm_Menu menuObj = MenuBackofficeData.Get.ByPermalinkWithRole(menuname, UserName);
            if (menuObj.Role == "N")
                return RedirectToAction("Index", "Permission", new { MenuName = "401" });

            int MenuID = menuObj?.ID ?? 0;
            name_menu = menuObj?.Menuname ?? "ไม่พบเมนู";
            ViewBag.Title = name_menu;
            ViewBag.MenuID = MenuID;
            ViewBag.Menuname = menuname;
            ViewBag.Role = menuObj.Role;
            if (!_cache.TryGetValue("LanguageList", out List<Languages> lang))
            {
                lang = LanguageData.GetByActive();
                MemoryCacheEntryOptions options = new MemoryCacheEntryOptions
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(365),
                    SlidingExpiration = TimeSpan.FromDays(365)
                };
                _cache.Set("LanguageList", lang, TimeSpan.FromDays(365));
            }
            List<PostsByLanguage> lstobj = new List<PostsByLanguage>();
            var MenuDisplay = MenuDisplayData.Get.ByMenu(MenuID);
            foreach (var a in lang)
            {
                PostsByLanguage obj = new PostsByLanguage();
                obj.SelectedTabs = a.LanguageCode == "TH" ? "active" : "";
                obj.LanguageCode = a.LanguageCode;
                obj.PostDetailLst = PostData.Get.ByMenu(MenuID, a.LanguageCode);
                obj.MenuDisplayID = MenuDisplay != null ? MenuDisplay.ID : 0;
                obj.SortingBy = MenuDisplay != null ? (MenuDisplay.SortingBy != null ? MenuDisplay.SortingBy.Value : 1) : 1;
                obj.SortingType = MenuDisplay != null ? (MenuDisplay.SortingType != null ? MenuDisplay.SortingType.Value : false) : false;
                lstobj.Add(obj);
            }
            ViewBag.Getsorting = DDLSortingForPostBy(MenuDisplay != null ? (MenuDisplay.SortingBy != null ? MenuDisplay.SortingBy.Value.ToString() : "1") : "1");
            return View(lstobj);

        }
        public IActionResult Manage(string menuname, string ID)
        {
            try
            {
                string name_menu = "";
                Tm_Menu menuObj = MenuBackofficeData.Get.ByPermalinkWithRole(menuname, UserName);
                if (menuObj.Role == "N")
                    return RedirectToAction("Index", "Permission", new { MenuName = "401" });

                int MenuID = menuObj?.ID ?? 0;
                name_menu = menuObj?.Menuname ?? "ไม่พบเมนู";
                ViewBag.Title = name_menu;
                ViewBag.MenuID = MenuID;
                ViewBag.Menuname = menuname;
                ViewBag.Role = menuObj.Role;
                if (MenuID == 0)
                    return RedirectToAction("Index", "Errorpage", new { MenuName = "404" });

                var obj = PostData.Get.PostsById(!string.IsNullOrEmpty(ID) ? int.Parse(ID) : 0).ToList();

                var main = !string.IsNullOrEmpty(ID) ? PostData.Get.MainPostsById(!string.IsNullOrEmpty(ID) ? int.Parse(ID) : 0) : new Posts();
                main = main == null ? new Posts() : main;
                if (main.InputDate == null)
                    main.InputDate = DateTime.Now;
                main.PostLst = obj;
                main.Menuname = menuname;
                main.MenuID = MenuID;
                main.GUID = Guid.NewGuid().ToString();
                TempData.Remove(main.GUID + "_TH");
                TempData.Remove(main.GUID + "_EN");
                return View("~/Views/Posts/Manage.cshtml", main);
            }
            catch (Exception ex)
            {
                LogTransaction.SaveLog(int.Parse(ID), LogTransaction.Get.ActivityType.Error, menuname, UserName, ex.Message, IpAddress, Browser);
            }
            return View(new Posts());
        }

        [HttpPost]
        //[ValidateInput(false)]
        public ActionResult Manage(Posts Posts, List<int> RelatedID)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    Posts.RelatedPost = String.Join(",", RelatedID);

                    var main = PostData.Post.AddOrUpdate(Posts, UserName, IpAddress, Browser);
                    foreach (var o in Posts.PostLst)
                    {
                        o.PostID = main.ID;
                        if(o.TagsName !=null && o.TagsName.Count() >0)
                        o.TagKeywords = String.Join(",", o.TagsName);
                    }
                    var detail = PostData.Post.DetailAddOrUpdate(Posts.PostLst, UserName, IpAddress, Browser);
                    foreach (var item in detail)
                    {
                        #region uploadfile
                        string tempUploads = TempData[item.SUB_GUID] != null ? Convert.ToString(TempData[item.SUB_GUID]) : "";
                        List<MediaFiles> lstUploads = !string.IsNullOrEmpty(tempUploads) ?
                          JsonConvert.DeserializeObject<List<MediaFiles>>(tempUploads) : new List<MediaFiles>();
                        if (lstUploads.Count() > 0)
                        {
                            foreach (var item2 in lstUploads)
                            {
                                var p = MediaFilesData.Post.UpdateStatus(item2.MediaFileID, item.PostDetailID.ToString(), UserName, IpAddress, Browser);
                            }
                        }

                        #endregion
                    }
                    main.PostLst = detail;

                    return RedirectToAction("Index", new { Menuname = main.Menuname });
                }
                catch (Exception ex)
                {
                    //LogModifyPage(state_GUID, Contents.FirstOrDefault().menuname, "ERROR :" + ex.GetType().Name, "ไม่สามารถทำการบันทึกข้อมูลได้เนื่องจาก" + ex.Message);
                    //Posts.lstobj = Contents;
                    //return View("~/Views/" + Config_static.Common.theme_name + "/Linker/Manage.cshtml", Posts);
                }
            }
            //Posts.lstobj = Contents;
            return View("~/Views/Posts/Manage.cshtml", Posts);
        }
        public JsonResult GetTags(string term)
        {
            var result = PostData.Get.TagsAll(term.ToLower());
            return Json(new { status = true, result });
        }

    }
}

Coding/Core.Backoffice/Views/PanelSystem/SettingFile/Index.cshtml
@model Core.DAL.Models.SettingFiles

@{ ViewBag.Title = "รายละเอียดตั้งค่าไฟล์";
    string role = (String)ViewBag.Role;

    }

<!-- start page title -->
<div class="content-header row">
    <div class="content-header-left col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">@ViewBag.Title</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index","Home")">หน้าหลัก</a>
                    </li>
                    <li class="breadcrumb-item">ตั้งค่าไฟล์</li>
                   
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->
<div class="content-body">
    <section id="basic">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-content">
                        <form asp-action="Index" asp-controller="SettingFile" method="POST" data-ajax-confirm="คุณต้องการบันทึกข้อมูลใช่หรือไม่ ?" data-ajax="true" data-ajax-success="redirect">
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => Model.ID)

                            <div class="card-body">
                                <div class="form-body">
                                    <div class="row justify-content-center">
                                        <div class="form-group col-md-6 col-12">
                                            <p>ชนิดไฟล์ที่อนุญาตให้แนบ <small class="text-danger">*จำเป็น</small></p>
                                            @Html.ListBoxFor(model => model.AllowTypeFileID, (SelectList)Core.Backoffice.Controllers.BaseController.GetExtension(Model.AllowTypeFileID), new { @class = "form-control select2-tags", @style = "width:100%", @data_live_search = "true", @placeholder = "ระบุคำค้นหาที่เกี่ยวข้อง", multiple = "multiple", @onkeydown = "return (event.keyCode!=13);" })
                                        </div>
                                    </div>
                                   
                                    <div class="row justify-content-center">
                                        <div class="form-group col-md-6 col-12">
                                            <p>ขนาดไฟล์ที่อนุญาตให้แนบทั้งหมด  (KB) <small class="text-danger">*จำเป็น</small></p>
                                            @Html.TextBoxFor(model => model.MaxSizeFile, new { @class = "form-control", @required = true, @placeholder = "ขนาดไฟล์ที่อนุญาตให้แนบทั้งหมด (KB)", @autocomplete = "off", @type = "number" })
                                        </div>
                                    </div>
                                    <div class="row justify-content-center">
                                        <div class="form-group col-md-6 col-12">
                                            <p>ขนาดไฟล์ที่อนุญาตให้แนบต่อ 1 ไฟล์ (KB) <small class="text-danger">*จำเป็น</small></p>
                                            @Html.TextBoxFor(model => model.SizeFile, new { @class = "form-control", @required = true, @placeholder = "ขนาดไฟล์ที่อนุญาตให้แนบต่อ 1 ไฟล์ (KB)", @autocomplete = "off", @type = "number" })
                                        </div>
                                    </div>
                                    <div class="row justify-content-center">
                                        <div class="form-group col-md-6 col-12">
                                            <p>จำนวนไฟล์ที่อนุญาตให้แนบ <small class="text-danger">*จำเป็น</small></p>
                                            @Html.TextBoxFor(model => model.MaxQuantityFile, new { @class = "form-control", @required = true, @placeholder = "จำนวนไฟล์ที่อนุญาตให้แนบ", @autocomplete = "off", @type = "number" })
                                        </div>
                                    </div>


                                </div>
                                <div class="form-actions text-right">
                                    <button type="submit" class="btn btn-info btn-min-width btn-glow mr-1 mb-1 "><i class="ft-save"></i> บันทึก</button>
                                    <button type="reset" class="btn btn-secondary btn-min-width btn-glow mr-1 mb-1 "><i class="ft-reset"></i> คืนค่า</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section SecAjaxConfig{
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery/dist/jquery.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery-unobtrusive-ajax/jquery.unobtrusive-ajax.js")"></script>
}
@section Scripts{
    <script async type="text/javascript" src="@Url.Content("~/app-assets/Framework/tables/jquery.treegrid.min.js")"></script>
    <script>
        $(function () {
             @if (role != "M")
               {
                   @: $("input, select, textarea, button").attr("disabled", true);
                   @:  $("button[type='submit'], button[type='reset'], input[type='submit'], input[type='reset']").remove();
                   @:  $(".SortingType, .switchForbidden, .bt-menustatus, .bt-status, .StatePublish, .switchACTIVE").each(function () { $(this).bootstrapSwitch('disabled', true); });
                    @:  $(".btn-social, .bt-delete, .or, .kv-file-remove").remove();
                 
               }
            if ($(".switchBootstrap").length > 0) {
                $('.switchBootstrap').bootstrapSwitch('size', 'small');
                $('.switchBootstrap').bootstrapSwitch('onColor', 'info');
                $('.switchBootstrap').bootstrapSwitch('onText', 'เปิด');
                $('.switchBootstrap').bootstrapSwitch('offText', 'ปิด');
            }
        })

         $(document).ajaxError(function (xhr, props) {
            if (props.status === 401) {
                window.location.href = '@Url.Action("Index", "Login")';
            }
         });

          $(document).ajaxComplete(function (a, xhr, c) {
            if (xhr.status === 403 && xhr.responseText.indexOf("LogOut") != -1) {
                Swal.fire({
                    title: 'Session timeout!',
                    text: "",
                    type: 'warning',
                    showCancelButton: false,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'ตกลง',
                    confirmButtonClass: 'btn btn-success',
                    cancelButtonClass: 'btn btn-danger ml-1',
                    buttonsStyling: false,
                }).then(function (result) {
                    if (result.value) {
                         window.location.href = "@Url.Action("Index", "Login")";
                    }
                })
            }
        });
        $('.confirmAddbtn').on('click', function () {
            if (!$("#myform")[0].checkValidity()) {
                $("#myform").submit();
                return false;
            }
            Swal.fire({
                title: 'คุณต้องการเพิ่มข้อมูล ?',
                text: "",
                type: 'warning',
                showCancelButton: false,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',

                confirmButtonText: 'ตกลง',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger ml-1',
                buttonsStyling: false,
            }).then(function (result) {
                if (result.value) {
                return false;
                } else {

                    return false;
                }
            })
        });
        function success_alert(tltle, detail) {
            toastr.success(detail, tltle
                , { "showMethod": "slideDown", "hideMethod": "slideUp", timeOut: 20000 });

        }
        function error_alert(tltle, detail) {
            toastr.success(detail, tltle
                , { "showMethod": "slideDown", "hideMethod": "slideUp", timeOut: 20000 });

        }
        $('.confirmCancelbtn').on('click', function () {
            Swal.fire({
                title: 'คุณต้องการยกเลิก ?',
                text: "",
                type: 'warning',
                showCancelButton: false,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',

                confirmButtonText: 'ตกลง',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger ml-1',
                buttonsStyling: false,
            }).then(function (result) {
                if (result.value) {

                      window.location.href = "@Url.Action("PageList", "Posts")";
                }
            })
        });

    </script>
}