Coding/Core.Backoffice/ViewComponent/MenuViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Common;
using Core.DAL.Models;
using Core.library;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace Core.Backoffice.Controllers
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IMemoryCache _cache;
        public MenuViewComponent(IMemoryCache memoryCache)
        {
            _cache = memoryCache;
        }
        public async Task<IViewComponentResult> InvokeAsync(int UserRoleGroupId, int Username)
        {
            //if (!_cache.TryGetValue("MenuList" + UserRoleGroupId.ToString(), out List<Tm_Menu> obj))
            //{
            List<Tm_Menu> list_menu = MenuBackofficeData.Get.GetMenuBackOfficeListActive();
            var role = RoleData.Get.RoleByGroupID(UserRoleGroupId).Where(o => o.RoleType != "N").ToList();
            List<Tm_Menu> obj = (from o in list_menu
                               join r in role on o.ID equals r.MenuID
                               where r.RoleType != "N"
                               select new
                               {
                                   o.ID
                                   ,
                                   o.img_front
                                   ,
                                   o.IsEdit
                                   ,
                                   o.LangCode
                                   ,
                                   o.levels
                                   ,
                                   o.link_front
                                   ,
                                   o.lstobj
                                   ,
                                   o.MENU_BACK_ID
                                   ,
                                   o.MENU_FRONT_ID
                                   ,
                                   o.menu_name_back
                                   ,
                                   o.Menuname
                                   ,
                                   o.MenuNameEN
                                   ,
                                   o.MenuNameTH
                                   ,
                                   o.MenuTypeCode
                                   ,
                                   o.newMenuDownloadID
                                   ,
                                   o.ParentMenuname
                                   ,
                                   o.permalink_back
                                   ,
                                   o.permalink_front
                                   ,
                                   o.RowNumber
                                   ,
                                   o.section_name_back
                                   ,
                                   o.self_back
                                   ,
                                   o.self_front
                                   ,
                                   o.Sequence
                                   ,
                                   o.show_back
                                   ,
                                   o.show_front
                                   ,
                                   o.sort_back
                                   ,
                                   o.sort_front
                                   ,
                                   o.Sub_Menu
                                   ,
                                   o.type_show
                                   ,
                                   o.UpdatedBy
                                   ,
                                   o.UpdatedDate
                                   ,
                                   o.action_back
                                   ,
                                   o.action_front
                                   ,
                                   o.Actived
                                   ,
                                   o.BelongID
                                   ,
                                   o.CategoryID
                                   ,
                                   o.controller_back
                                   ,
                                   o.controller_front
                                   ,
                                   o.CreatedBy
                                   ,
                                   o.CreatedDate

                                   ,
                                   o.Disabled
                                   ,
                                   o.FPermalink
                                   ,
                                   o.icon_back
                                   ,
                                   o.icon_front

                               }).ToList_list<Tm_Menu>();
            //    MemoryCacheEntryOptions options = new MemoryCacheEntryOptions
            //    {
            //        AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(1), // cache will expire in 25 seconds   TimeSpan.FromSeconds(25)
            //                                                                // SlidingExpiration = TimeSpan.FromMinutes(30) // caceh will expire if inactive for 5 seconds    FromSeconds(5)
            //    };
            //    //options.RegisterPostEvictionCallback(Callback, "Some state info");
            //    _cache.Set("MenuList" + UserRoleGroupId.ToString(), obj, TimeSpan.FromDays(1));
            //}


            List<MenuGenBackoffice> result_menu = new List<MenuGenBackoffice>();
            result_menu = obj.GroupBy(o => o.section_name_back).Select(g => new { section_name_back = g.Key, lstobj = g.ToList() }).ToList_list<MenuGenBackoffice>();
            return await Task.FromResult((IViewComponentResult)View("Default", result_menu));
        }
       
    }
    //public class LogsTabViewComponent : ViewComponent
    //{
    //    public async Task<IViewComponentResult> InvokeAsync(string LangID, string Menuname)
    //    {
    //        return View("~/Views/PanelSystem/Logs/_list.cshtml");
    //    }
    //}
  
}

Coding/Core.Backoffice/Views/Shared/_Footer.cshtml
<footer class="footer footer-static footer-dark navbar-shadow  navbar-border ">
    <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
        <span class="float-md-left d-block d-md-inline-block">© สงวนลิขสิทธิ์ 2566 : บัณฑิตวิทยาลัย มหาวิทยาลัยศรีนครินทรวิโรฒ v2.0 </span>
        <span class="float-md-right d-none d-lg-block">
            <span id="scroll-top"></span>
        </span>
    </p>
</footer>

Coding/Core.Backoffice/Views/Shared/_Header.cshtml
@using System.Threading
@using System.Security.Claims
@{

    string FullName = ((ClaimsIdentity)User.Identity).FindFirst("FullName").Value;
}
<nav
    class="header-navbar navbar-expand-lg navbar navbar-with-menu navbar-without-dd-arrow navbar-semi-dark  fixed-top navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-lg-none mr-auto"><a
                        class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                            class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item mr-auto">
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                        <img class="brand-logo" alt="logo" src="@Url.Content("~/app-assets/images/Logo/android-icon-192x192.png?v=1")">
                        <h3 class="brand-text">Back Office</h3>
                    </a>
                </li>
                @*<li class="nav-item d-none d-lg-block nav-toggle"><a class="nav-link modern-nav-toggle pr-0"
                    data-toggle="collapse"><i class="toggle-icon ft-toggle-right font-medium-3 white"
                    data-ticon="ft-toggle-right"></i></a></li>*@
                <li class="nav-item d-lg-none"><a class="nav-link open-navbar-container" data-toggle="collapse"
                        data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                </ul>
                <ul class="nav navbar-nav float-right">
                    <li class="dropdown notification-list">
                        <a class="nav-link dropdown-toggle nav-user mr-0" data-toggle="dropdown" href="#" role="button">
                            <span class="pro-user-name ml-1">
                                @FullName
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated profile-dropdown">
                            @*<a href="@Url.Action("Profile","Users")" class="dropdown-item notify-item">
                                <i class="ft-user"></i>
                                <span>แก้ไขข้อมูลส่วนตัว</span>
                                </a>*@
                            <a href="@Url.Action("changepass","Users")" class="dropdown-item notify-item">
                                <i class="la la-key"></i>
                                <span>เปลี่ยนรหัสผ่าน</span>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a id="logout" class="dropdown-item"><i class="ft-power"></i> ออกจากระบบ</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

Coding/Core.Backoffice/Views/Shared/_Layout.cshtml
@using Core.Common
@using Core.Backoffice.Controllers
@{
    int curUserRoleGroupId = Int32.Parse(User.FindFirst("RoleGroupID").Value);
    // bool chRole = true;
    // try
    // {
    // string curMenu = ViewBag.Title;
    // var sMenuId = StaticMenu.GetMenuIdByName(curMenu).ToString();
    // chRole = BaseController.AuthorizeMenu(sMenuId, curUserRoleGroupId);
            // }
    // catch { }
}
@{
    string ver_asset = "2406060901";
    string Mode = "";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - BACKOFFICE</title>
    <link rel="apple-touch-icon" sizes="57x57"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-57x57.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="60x60"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-60x60.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="72x72"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-72x72.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="76x76"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-76x76.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="114x114"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-114x114.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="120x120"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-120x120.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="144x144"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-144x144.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="152x152"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-152x152.png?v="+@ver_asset)">
    <link rel="apple-touch-icon" sizes="180x180"
        href="@Url.Content("~/app-assets/images/Logo/apple-icon-180x180.png?v="+@ver_asset)">
    <link rel="icon" type="image/png" sizes="192x192"
        href="@Url.Content("~/app-assets/images/Logo/android-icon-192x192.png?v="+@ver_asset)">
    <link rel="icon" type="image/png" sizes="32x32"
        href="@Url.Content("~/app-assets/images/Logo/favicon-32x32.png?v="+@ver_asset)">
    <link rel="icon" type="image/png" sizes="96x96"
        href="@Url.Content("~/app-assets/images/Logo/favicon-96x96.png?v="+@ver_asset)">
    <link rel="icon" type="image/png" sizes="16x16"
        href="@Url.Content("~/app-assets/images/Logo/favicon-16x16.png?v="+@ver_asset)">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="@Url.Content("~/app-assets/images/Logo/ms-icon-144x144.png")">
    <meta name="theme-color" content="#ffffff">

    @*<link rel="apple-touch-icon" href="@Url.Content("~/app-assets/images/Logo/apple-icon-120x120.png?v="+@ver_asset)">
        <link rel="shortcut icon" type="image/x-icon"
        href="@Url.Content("~/app-assets/images/Logo/favicon.ico?v="+@ver_asset)">*@
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/fonts/fonts.css?v="+@ver_asset)">
    <link href="@Url.Content("~/fontawesome/all.css")" rel="stylesheet">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/fonts/font-awesome.min.css?v="+@ver_asset)" />


    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/Framework/vendors.min.css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/fullcalendar/fullcalendar.min.css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/tables/dataTables.bootstrap4.min.css?v="+@ver_asset)">

    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/animate/animate.css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/popup/sweetalert2.min.css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/Framework/popup/toastr.css?v="+@ver_asset)">

  
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/forms/toggle/bootstrap-switch"+Mode+".css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/forms/selects/select2.min.css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/forms/pickers/bootstrap-datepicker.css")">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/forms/pickers/daterangepicker.css?v="+@ver_asset)">
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/css/bootstrap"+Mode+".css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/css/bootstrap-extended"+Mode+".css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/css/colors"+Mode+".css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/css/components.css?v="+@ver_asset)">


    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/Framework/charts/morris.css")">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/Framework/charts/chartist.css")">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/charts/chartist-plugin-tooltip.css")">
    <!-- END: Theme CSS-->
    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/css/vertical-menu-modern"+Mode+".css?v="+@ver_asset)">

    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/css/palette-gradient"+Mode+".css?v="+@ver_asset)">

    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/forms/fileinput/fileinput"+Mode+".css?v="+@ver_asset)">
    <link rel="stylesheet" type="text/css"
        href="@Url.Content("~/app-assets/Framework/forms/fileinput/theme.min.css?v="+@ver_asset)">
 
    <!-- END: Page CSS-->
    <!-- BEGIN: Custom CSS-->
    @*<link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/css/style.css?v="+@ver_asset)">*@
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/css/style.css")">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/app-assets/css/jquery-confirm.min.css")">
    <!-- END: Custom CSS-->

</head>

<body class="vertical-layout vertical-menu-modern 2-columns fixed-navbar" data-open="click"
      data-menu="vertical-menu-modern" data-col="2-columns">
    <!-- BEGIN: Header-->
    @await Html.PartialAsync("~/Views/Shared/_Header.cshtml")
    <!-- END: Header-->
    <!-- BEGIN: Main Menu-->
    @await Component.InvokeAsync("Menu", new { UserRoleGroupId = curUserRoleGroupId })
    @*@await Html.PartialAsync("~/Views/Shared/_menu.cshtml")*@
    <!-- END: Main Menu-->
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            @RenderBody()
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    @await Html.PartialAsync("~/Views/Shared/_Footer.cshtml")
    <!-- END: Footer-->

    @RenderSection("SecAjaxConfig", required: false)

    <!-- BEGIN: Vendor JS-->
    <script src="@Url.Content("~/app-assets/js/vendors.min.js?v="+@ver_asset)"></script>
    <!-- END Vendor JS-->
    <!-- BEGIN: Page Vendor JS-->
    <script src="@Url.Content("~/app-assets/js/jquery.sticky.js?v="+@ver_asset)"></script>

    <script src="@Url.Content("~/app-assets/Framework/forms/fileinput/fileinput.min.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/Framework/forms/fileinput/theme.min.js?v="+@ver_asset)"></script>


    <script src="@Url.Content("~/app-assets/Framework/popup/toastr.min.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/Framework/popup/sweetalert2.all.min.js?v="+@ver_asset)"></script>

    <script src="@Url.Content("~/app-assets/Framework/forms/selects/select2.full.min.js")"></script>
    <script src="@Url.Content("~/app-assets/Framework/tables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/app-assets/Framework/tables/dataTables.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/app-assets/Framework/charts/chartist.min.js")"></script>
    <script src="@Url.Content("~/app-assets/Framework/charts/chartist-plugin-tooltip.min.js")"></script>

    <script src="@Url.Content("~/app-assets/Framework/charts/morris.min.js")"></script>
    <!-- END: Page Vendor JS-->
    <!-- BEGIN: Theme JS-->
    <script src="@Url.Content("~/app-assets/js/app-menu"+Mode+".js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/js/app"+Mode+".js?v="+@ver_asset)"></script>


    <script src="@Url.Content("~/app-assets/Framework/forms/toggle/bootstrap-switch"+Mode+".js?v="+@ver_asset)"></script>


    <script src="@Url.Content("~/app-assets/Framework/forms/pickers/bootstrap-datepicker.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/Framework/forms/pickers/bootstrap-datepicker-thai.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/Framework/forms/pickers/bootstrap-datepicker.th.js?v="+@ver_asset)"></script>

    <!-- END: Theme JS-->

    <script src="@Url.Content("~/app-assets/js/CustomFileInput.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/js/extensions.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/js/site.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/app-assets/js/ActionSite.js?v="+@ver_asset)"></script>
    <script src="@Url.Content("~/dashboard-ecommerce.js")"></script>
    <script src="@Url.Content("~/app-assets/js/jquery-confirm.min.js")"></script>
    <script src="@Url.Content("~/app-assets/js/jquery.multisortable.js")"></script>
    @RenderSection("Scripts", required: false)

</body>

</html>