Coding/Core.Backoffice/Controllers/ActionScriptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Common;
using Core.DAL.Models;
using Core.library;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Wangkanai.Detection;

namespace Core.Backoffice.Controllers
{
    [Authorize]
    [ActiveUserFilter]
    public class ActionScriptsController :  BaseController
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IHttpContextAccessor _accessor;
        private readonly IBrowserResolver _browser;
        private static string IpAddress;
        private static string Browser;
        private readonly IMemoryCache _cache;
        public ActionScriptsController(IWebHostEnvironment environment, IHttpContextAccessor httpContextAccessor, IBrowserResolver browserDetector, IMemoryCache memoryCache)
        {
            _environment = environment;
            _accessor = httpContextAccessor;
            _browser = browserDetector;
            IpAddress = _accessor.HttpContext.Connection.RemoteIpAddress.ToString();
            Browser = _browser.Browser.Type.ToString();
            _cache = memoryCache;
        }
        [HttpPost]
        public JsonResult UpdateSorting(string MenuDisplayID, string MenuID, string SortingBy,int ActionType)
        {
            bool Results = false;
            if(ActionType ==1)
                Results = MenuDisplayData.Post.UpdateSortingBy(Int32.Parse(MenuDisplayID), Int32.Parse(MenuID), Int32.Parse(SortingBy),UserName, IpAddress, Browser);
            else
                Results = MenuDisplayData.Post.UpdateSortingType(Int32.Parse(MenuDisplayID), Int32.Parse(MenuID), Boolean.Parse(SortingBy), UserName, IpAddress, Browser);

            return Json(new { status = Results, message = "พบข้อผิดพลาดกรุณาลองใหม่ หรือ ติดต่อผู้ดูแลระบบ"});
        }

        [HttpPost]
        public JsonResult Delete(int RoleGroupID)
        {
            try
            {
                var Items = RoleData.Post.Delete(RoleGroupID, UserName, IpAddress, Browser);
                return Json(new { status = true, Items });
            }
            catch (Exception ex)
            {
                return Json(new { status = true, message = ex.Message.ToString() });
            }
        }
        [HttpPost]
        public JsonResult UpdateSequence(int ID, string Menuname, string MenuType, string Seq)
        {
            ResponseJson ResponseData = new ResponseJson();
            try
            {
                switch (MenuType)
                {
                    case "BANNER":
                        ResponseData = BannerData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "JOBS":
                        ResponseData = JobPositionData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "POSTS":
                        ResponseData = PostData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "FAQ":
                        ResponseData = FaqData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "DOWNLOAD":
                        ResponseData = DownloadFormData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "RSSFeed":
                        ResponseData = RSSFeedData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "STAFF":
                        ResponseData = StaffData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "WBTOPIC":
                        ResponseData = WBTopicData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "SHORTCUT":
                        ResponseData = MenuFrontData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MENU":
                        ResponseData = MenuBackofficeData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        SetNewMenu(UserRoleGroupId);
                        break;
                    case "CATEGORY":
                        ResponseData = CategoryData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MASTER":
                        ResponseData = MasterData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "PROJECTS":
                        ResponseData = ProjectsData.Post.UpdateSequence(ID, int.Parse(Seq), UserName, IpAddress, Browser, Menuname);
                        break;
                        
                    default:
                        ResponseData.Result = false;
                        ResponseData.MessageError = "Default";
                        break;
                }
                return Json(ResponseData);
            }
            catch (Exception ex)
            {
                return Json(new { status = true, message = ex.Message.ToString() });
            }
        }
        [HttpPost]
        public JsonResult UpdateStatus(int ID,string Menuname, string MenuType, string state)
        {
            ResponseJson ResponseData = new ResponseJson();
            try
            {
                
                switch (MenuType)
                {
                    case "CATEGORY":    ResponseData = CategoryData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "BANNER":
                                        ResponseData = BannerData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "JOBS":
                                        ResponseData = JobPositionData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "POSTS":
                                        ResponseData = PostData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "FAQ":
                                        ResponseData = FaqData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "DOWNLOAD":
                                        ResponseData = DownloadFormData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "RSSFeed":
                                        ResponseData = RSSFeedData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                                        break;
                    case "STAFF":
                        ResponseData = StaffData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                 
                    case "WBTOPIC":
                        ResponseData = WBTopicData.Post.Forbidden(ID, bool.Parse(state),"", UserName, IpAddress, Browser, Menuname);
                        break;
                    case "WBWAITTING":
                        ResponseData = WBTopicData.Post.Approved(ID, bool.Parse(state),"", UserName, IpAddress, Browser, Menuname);
                        break;
                     case "COMPLAINTTYPE":
                        ResponseData = ComplaintTypeData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "SHORTCUT":
                        ResponseData = MenuFrontData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MENU":
                        ResponseData = MenuBackofficeData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        SetNewMenu(UserRoleGroupId);
                        break;
                    case "ROLEGROUP":
                        ResponseData = RoleData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                 
                    case "MEMBER":
                        ResponseData = MemberData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "WBREPLY":
                        ResponseData = WBReplyData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "CHANNELCOMMENTTYPE":
                        ResponseData = ChannelCommentTypeData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "MASTER":
                        ResponseData = MasterData.Post.UpdateStatus(ID, bool.Parse(state), UserName, IpAddress, Browser, Menuname);
                        break;
                    case "USER":

Coding/Core.Backoffice/Controllers/Banner_and_Link/PopupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Core.Common;
using Core.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Wangkanai.Detection;

namespace Core.Backoffice.Controllers
{
    [Authorize]
    [ActiveUserFilter]
    public class PopupController : BaseController
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IHttpContextAccessor _accessor;
        private readonly IBrowserResolver _browser;
        private static string IpAddress;
        private static string Browser;
        private readonly IMemoryCache _cache;
        
        public PopupController(IWebHostEnvironment environment, IHttpContextAccessor httpContextAccessor, IBrowserResolver browserDetector,IMemoryCache memoryCache)
        {
            _environment = environment;
            _accessor = httpContextAccessor;
            _browser = browserDetector;
            IpAddress = _accessor.HttpContext.Connection.RemoteIpAddress.ToString();
            Browser = _browser.Browser.Type.ToString();
            _cache = memoryCache;
        }
        public IActionResult Index(string menuname)
        {
            string name_menu = "";
            Tm_Menu menuObj = MenuBackofficeData.Get.ByPermalinkWithRole(menuname, UserName);
            if (menuObj.Role == "N")
                return RedirectToAction("Index", "Permission", new { MenuName = "401" });

            int MenuID = menuObj?.ID ?? 0;
            name_menu = menuObj?.Menuname ?? "ไม่พบเมนู";
            ViewBag.Title = name_menu;
            ViewBag.MenuID = MenuID;
            ViewBag.Menuname = menuname;
            ViewBag.Role = menuObj.Role;
            if (_cache.TryGetValue("LanguageList", out List<Languages> lang))
            {
                lang = LanguageData.GetByActive();
            }
            List<BannerByLanguage> lstobj = new List<BannerByLanguage>();
            var MenuDisplay = MenuDisplayData.Get.ByMenu(MenuID);
             foreach (var a in lang)
            {
                TempData.Remove(MenuID + "_" + a.LanguageCode);
                BannerByLanguage obj = new BannerByLanguage();
                obj.SelectedTabs = a.LanguageCode == "TH" ? "active" : "";
                obj.LanguageCode = a.LanguageCode;
                obj.lstBanner = BannerData.Get.ByMenu(MenuID, a.LanguageCode);
                
                obj.MenuDisplayID = MenuDisplay != null ? MenuDisplay.ID : 0;
                obj.SortingBy = MenuDisplay != null ? (MenuDisplay.SortingBy !=null ? MenuDisplay.SortingBy.Value: 1):1;
                obj.SortingType = MenuDisplay != null ? (MenuDisplay.SortingType != null ? MenuDisplay.SortingType.Value : false):false;
                lstobj.Add(obj);
            }
            ViewBag.Getsorting = DDLSortingBy(MenuDisplay != null ? (MenuDisplay.SortingBy != null ? MenuDisplay.SortingBy.Value.ToString() : "1") : "1");
            LogTransaction.SaveLog(0, LogTransaction.Get.ActivityType.View, name_menu, UserName, "", IpAddress, Browser);

            return View("~/Views/banner_and_link/Popup/index.cshtml", lstobj);

        }
        public IActionResult Manage(string menuname, string ID)
        {
            int refID = !string.IsNullOrEmpty(ID) ? Convert.ToInt32(ID) : 0;
            string name_menu = "";
            try
            {
                Tm_Menu menuObj = MenuBackofficeData.Get.ByPermalinkWithRole(menuname, UserName);
                if (menuObj.Role == "N")
                    return RedirectToAction("Index", "Permission", new { MenuName = "401" });

                int MenuID = menuObj?.ID ?? 0;
                name_menu = menuObj?.Menuname ?? "ไม่พบเมนู";
                ViewBag.Title = name_menu;
                ViewBag.MenuID = MenuID;
                ViewBag.Menuname = menuname;
                ViewBag.Role = menuObj.Role;
                if (MenuID == 0)
                    return RedirectToAction("Index", "Errorpage", new { MenuName = "404" });

                var main = !string.IsNullOrEmpty(ID)?BannerData.Get.MainBannerById(!string.IsNullOrEmpty(ID) ? int.Parse(ID) : 0) : new Banner();
                var obj = BannerData.Get.BannerById(!string.IsNullOrEmpty(ID)?int.Parse(ID):0).ToList();
                main = main == null ? new Banner() : main;
                main.MenuID = MenuID;
                main.lstBanner = obj;
                string logDescription = "";
                if (obj.Count > 0)
                {
                    logDescription = "ดูรายละเอียดข้อมูล Popup Name : " + obj.FirstOrDefault().BannerName;
                }
                LogTransaction.SaveLog(refID, LogTransaction.Get.ActivityType.View, name_menu, UserName, logDescription, IpAddress, Browser);

                return View("~/Views/banner_and_link/Popup/Manage.cshtml", main);
            }
            catch (Exception ex)
            {
                LogTransaction.SaveLog(refID, LogTransaction.Get.ActivityType.Error, name_menu, UserName, ex.Message, IpAddress, Browser);
            }
                //return View("~/Views/banner_and_link/Popup/Manage.cshtml", new Banner());
                return RedirectToAction("Index", new { Menuname = menuname });
        }
        [HttpPost]
        //[ValidateInput(false)]
        public ActionResult Manage(Banner banner)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    var main = BannerData.Post.AddOrUpdate(banner,UserName, IpAddress, Browser);
                    foreach(var o in banner.lstBanner)
                    {
                        o.BannerID = main.ID;
                    }
                    var detail = BannerData.Post.DetailAddOrUpdate(banner.lstBanner, UserName,12, IpAddress, Browser);
                    main.lstBanner = detail;
                    return RedirectToAction("Index", new { Menuname = main.Menuname });
                }
                catch (Exception ex)
                {
                    LogTransaction.SaveLog(banner.ID, LogTransaction.Get.ActivityType.Error, banner.Menuname, UserName, ex.Message, IpAddress, Browser);
                }
            }
                return View("~/Views/banner_and_link/Popup/Manage.cshtml", banner);
        }
    }
}

Coding/Core.Backoffice/Views/Banner_and_Link/Popup/Manage.cshtml
@model Core.DAL.Models.Banner
@{
    ViewBag.Title2 = "รายละเอียดข้อมูล"+ViewBag.Title;
    string role = (String)ViewBag.Role;

 }
<style>
    .switchBootstrap {
        min-width: 450px !important;
        width: 200px !important;
    }

    .kv-file-remove {
        display: none;
    }
</style>
<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">@ViewBag.Title</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="@Url.Action("Index","Home")">หน้าหลัก</a>
                    </li>
                    <li class="breadcrumb-item active">
                        @ViewBag.Title2
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <div class="content-header-right col-md-3 col-12">
        <div class="btn-group float-md-right">
            <a href="@Url.Action("Index", new {menuname = ViewBag.Menuname})" class="btn btn-social btn-min-width mr-1 mb-1 btn-secondary"><i class="la la-angle-left"></i> กลับ &nbsp;&nbsp;</a>
        </div>
    </div>
</div>
<div class="content-body" id="Cont">
    <section id="basic-form-layouts">
        <div class="row">
            <div class="col-12">
                <div class="card">

                    <div class="card-content collapse show">
                        <div class="card-body">

                            @using (Html.BeginForm("Manage", "Popup", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.HiddenFor(model => Model.MenuID)
                                @Html.HiddenFor(model => Model.CreatedDate)
                                @Html.HiddenFor(model => Model.CreatedBy)
                                @Html.HiddenFor(model => Model.ID)
                                @Html.HiddenFor(model => Model.Menuname)
                                <div class="card-content">
                                    @*<div class="row justify-content-center">
                                        <div class="btn-group form-group float-md-right">
                                            @if (Model.ID > 0)
                                            {
                                                @: ข้อมูลล่าสุดโดย @Model.UpdatedBy เมื่อ @Model.UpdatedDate_Str
                                            }
                                        </div>
                                    </div>*@
                                   

                                    <ul class="nav nav-tabs nav-underline nav-top-border no-hover-bg">
                                        @await Component.InvokeAsync("LanguageTab")
                                    </ul>

                                    <div class="tab-content px-1 pt-1">
                                        @foreach (var itemdetail in Model.lstBanner)
                                        {
                                            itemdetail.BannerID = Model.ID;
                                            itemdetail.MenuID = Model.MenuID;
                                            itemdetail.Menuname = Model.Menuname;
                                            await Html.RenderPartialAsync("~/Views/Banner_and_Link/Popup/_Manage.cshtml", itemdetail);
                                        }
                                        <hr />
                                        <div class="row justify-content-center">

                                            <div class="form-group row">
                                                <div class="col-md-6">
                                                    <label>ช่วงวันที่เผยแพร่</label>
                                                    <div class="col-12">
                                                        <div class="input-group input-daterange date">
                                                            @Html.TextBoxFor(model => Model.EffectiveDate_str, "{0:dd/MM/yyyy}", new Dictionary<string, object> { { "id", "EffectiveDate" }, { "class", "form-control" }, { "placeholder", "วันที่เริ่นต้นแสดงผล" }, { "autocomplete", "off" }, { "data-provide", "datepicker" }, { "data-date-language", "th-th" } })
                                                            <div class="input-group-append">
                                                                <span class="input-group-text" id="sizing-addon2"> ถึง </span>
                                                            </div>
                                                            @Html.TextBoxFor(model => Model.EndDate_str, "{0:dd/MM/yyyy}", new Dictionary<string, object> { { "id", "EndDate" }, { "class", "form-control" }, { "placeholder", "วันที่สิ้นสุดแสดงผล" }, { "autocomplete", "off" }, { "data-provide", "datepicker" }, { "data-date-language", "th-th" } })
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <label for="active">สถานะการเผยแพร่</label>
                                                   
                                                    <div class="col-12">
                                                        @Html.CheckBoxFor(model => model.Actived, new { @id = "active", @class = "StatePublish" })
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="form-actions text-right">
                                            <button type="submit" class="btn btn-info btn-min-width btn-glow mr-1 mb-1 "><i class="ft-save"></i> บันทึก</button>
                                            <button type="reset" class="btn btn-secondary btn-min-width btn-glow mr-1 mb-1 "><i class="ft-reset"></i> คืนค่า</button>
                                        </div>
                                    </div>
                                </div>
                              }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section SecAjaxConfig{
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery/dist/jquery.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery-validation/dist/jquery.validate.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/app-assets/Framework/jquery-unobtrusive-ajax/jquery.unobtrusive-ajax.js")"></script>
}
@section Scripts{
    

    <script async type="text/javascript" src="@Url.Content("~/app-assets/js/MasterCustomFile.js")"></script>
    <script>
        function delf(i) {
            var urlz = "@Url.Action("RemoveFile", "ActionScripts", new { FileID = Model.ID.ToString() })";
            $.ajax({
                type: "GET",
                url: urlz,
                dataType: 'json',
                data: {
                    i: i
                },
                success: function (response) {
                    if (response != null) {
                        return true;
                    }
                    return false;
                }
            });
        }
        $(document).ready(function () {
             @if (role != "M")
               {
                   @: $("input, select, textarea, button").attr("disabled", true);
                   @:  $("button[type='submit'], button[type='reset'], input[type='submit'], input[type='reset']").remove();
                   @:  $(".SortingType, .switchForbidden, .bt-menustatus, .bt-status, .StatePublish, .switchACTIVE").each(function () { $(this).bootstrapSwitch('disabled', true); });
                    @:  $(".btn-social, .bt-delete, .or, .kv-file-remove").remove();
                   @: if ($('.summernote').length > 0) { $('.summernote').summernote('disable'); }
                   @: $('a[title="Edit"]').each(function () {$(this).attr('title', 'View'); $(this).find('span.la.la-pencil-square-o').each(function () { $(this).removeClass('la la-pencil-square-o'); $(this).addClass('la la-eye'); }); });
               }
            if ($('.fileImage').length > 0) {
                $('.fileImage').attr("accept", "image/*");



            }

        })
    </script>
}